---
name: On Demand Workflow
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
      environment:
        description: 'Environment (dev, tst, or stg)'
        required: true
        default: 'stg'
      runsOn:
        description:
        required: true
        default: "ubuntu-latest"

jobs:
  on_trigger:
    environment:
      name: ${{ github.event.inputs.environment }}
    name: "Manual JOB"
    runs-on: ["${{ github.event.inputs.runsOn }}"]

    container:
      image: python:3.9

    steps:
    - uses: actions/checkout@v2
    - name: Main
      env:
        MY_SECRET: ${{ secrets.MY_SECRET }}
      run: |
        uname -a
        echo "running in ${{ github.event.inputs.environment }}"
        echo "running on ${{ github.event.inputs.runsOn }}"
        echo "running with ${{ github.event.inputs.logLevel }}"
        python -c "import os; print(list(os.environ.get('MY_SECRET', [])))"
